export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const MODIFY_EMPLOYEE = "MODIFY_EMPLOYEE";
export const EMPLOYEE_SELECTED = "EMPLOYEE_SELECTED";
export const GET_EMPLOYEE = "GET_EMPLOYEE";


